---
name: Build-Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build-test:
    env:
      AIRFLOW_HOME: ${{ github.workspace }}
    name: Install airtigrs
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install package
        run: |
          # Lock on a specific commit until version is released on PyPI
          pip install git+https://github.com/TIGRLab/datman.git@a0cd1ffd443d72a80b0b8dd4bcaa10c0307c4b4f
          pip install -q -e .[buildtest]

      - name: Run unit tests
        run: |
          cd $AIRFLOW_HOME/airtigrs
          ls
          py.test . -v
